PicShare_GCPDemo/Models/CloudStorageOptions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PicShare_GCPDemo.Models
{
    public class CloudStorageOptions
    {
        public string BucketName { get; set; }
        public string ObjectName { get; set; } = "sample.txt";
    }
}

PicShare_GCPDemo/Models/ErrorViewModel.cs
using System;

namespace PicShare_GCPDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PicShare_GCPDemo/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PicShare_GCPDemo.Models
{
    public class Picture
    {
        public int PictureId { get; set; }
        public string FilePath { get; set; }
        public string Caption { get; set; }
        public DateTimeOffset AddedDate { get; set; }
    }
}

PicShare_GCPDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PicShare_GCPDemo.Models;
using Microsoft.EntityFrameworkCore;

namespace PicShare_GCPDemo.Controllers
{
    public class HomeController : Controller
    {
        PicShareContext _context;

        public HomeController(PicShareContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DbTest()
        {
            var model = _context.Picture.OrderBy(p => p.AddedDate).Take(5).ToList();
            return View(model);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PicShare_GCPDemo/Controllers/PicturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PicShare_GCPDemo.Models;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace PicShare_GCPDemo.Controllers
{
    [Produces("application/json")]
    [Route("api/Pictures")]
    public class PicturesController : Controller
    {
        private readonly PicShareContext _context;
        private readonly IHostingEnvironment _env;

        public PicturesController(PicShareContext context, IHostingEnvironment environment)
        {
            _context = context;
            _env = environment;
        }

        // POST: api/Pictures
        [HttpPost]
        public async Task<IActionResult> PostPicture(IFormFile image, string caption)
        {
            var filename = await SaveImage(image);
            var picture = new Picture
            {
                AddedDate = DateTimeOffset.Now,
                Caption = caption,
                FilePath = "/images/pics/" + filename
            };

            _context.Picture.Add(picture);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetPicture", new { id = picture.PictureId }, picture);
        }

        private async Task<string> SaveImage(IFormFile file)
        {
            var path = GetFilePath(file.FileName);

            if (file.Length > 0)
            {
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }

            return path.Substring(path.LastIndexOf(Path.DirectorySeparatorChar) + 1);
        }

        private string GetFilePath(string localFilename)
        {
            // get the full path to the file
            var tempName = Path.GetRandomFileName();
            var name = tempName.Substring(0, tempName.IndexOf('.')) + 
                localFilename.Substring(localFilename.IndexOf('.'));

            // create the path
            var sep = Path.DirectorySeparatorChar;
            var filePath = _env.WebRootPath + sep + "images" + sep + "pics" + sep + name;
            return filePath;
        }

        // GET: api/Pictures
        [HttpGet]
        public IEnumerable<Picture> GetPicture(string search, int take = 15, int offset = 0)
        {
            if (string.IsNullOrWhiteSpace(search))
                return _context.Picture
                    .OrderByDescending(p => p.AddedDate)
                    .Take(take)
                    .Skip(offset);
            else
                return _context.Picture
                    .Where(p => p.Caption.Contains(search))
                    .OrderByDescending(p => p.AddedDate)
                    .Take(take)
                    .Skip(offset);
        }
    }
}

PicShare_GCPDemo/Views/Home/DbTest.cshtml
@model IEnumerable<PicShare_GCPDemo.Models.Picture>

@{
    ViewData["Title"] = "DbTest";
}

<h2>DbTest</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.FilePath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Caption)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AddedDate)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FilePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Caption)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PictureId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PictureId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PictureId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PicShare_GCPDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "PicShare!";
}

<form class="form-inline" data-bind="submit: searchPics">
    <div class="form-group has-feedback">
        <label class="sr-only" for="imageSearch">Search</label>
        <div class="input-group">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </span>
            <input id="imageSearch" type="search" data-bind="textInput: searchText"
                   class="form-control" placeholder="Search images" 
                   aria-describedby="inputSuccess2Status">
        </div>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
</form>

<section data-bind="visible: shouldShowUpload">
    <h1>Upload a Pic!</h1>
    <form id="uploadForm" data-bind="submit: upload" method="post" enctype="multipart/form-data"
          asp-controller="Pictures" asp-action="PostPicture">
        <div class="form-group">
            <label for="image">Image:</label>
            <input id="image" name="image" type="file" />
        </div>
        <div class="form-group">
            <label for="caption">Caption:</label>
            <input id="caption" name="caption" type="text" placeholder="Caption" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</section>

<section id="searchResults">
    <h1>Results <span data-bind="text: pics().length"></span></h1>
    <div class="picsContainer" data-bind="foreach: pics">
        <div class="picResult">
            <img alt="" data-bind="attr: { src: filePath }" class="img-responsive" />
            <p data-bind="text: caption"></p>
        </div>
    </div>
</section>

PicShare_GCPDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pic Share</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Head", required: false)
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <img id="logo" src="~/images/photosIcon.png" alt="" />
                    <span id="siteName">Pic Share</span>
                </a>
            </div>
            <div class="navbar-collapse collapse pull-right">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a data-bind="click: toggleUpload">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        Upload
                    </a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">
                        <span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
                        Slideshow
                    </a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Pic Share</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script type='text/javascript' src="~/lib/knockout/dist/knockout.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script type='text/javascript' src="~/lib/knockout/dist/knockout.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>